import { test, expect } from '@playwright/test';

// test('test', async ({ page }) => {
//   await page.goto('https://testschool.launchmysite.in/');
//   await page.getByPlaceholder('Enter your Email').click();
//   await page.getByPlaceholder('Enter your Email').fill('test@example.com');
//   await page.getByPlaceholder('Enter your password').click();
//   await page.getByPlaceholder('Enter your password').fill('test@123');
//   await page.getByRole('button', { name: 'Sign In' }).click();
//   await page.getByText('School Details').click();
//   await page.locator('div').filter({ hasText: /^School Name\*$/ }).locator('div').nth(3).click();
//   await page.getByPlaceholder('Enter your school name').fill('test school');
//   await page.locator('div').filter({ hasText: /^School Code$/ }).locator('div').nth(3).click();
//   await page.getByPlaceholder('Enter your school code').fill('001');
//   await page.getByPlaceholder('YYYY').click();
//   await page.getByPlaceholder('YYYY').fill('2000');
//   await page.getByPlaceholder('Ex:').click();
//   await page.getByRole('button', { name: 'create' }).click();
//   await page.getByRole('listbox', { name: 'Affiliated with*' }).click();
//   await page.getByLabel('CBSE', { exact: true }).getByText('CBSE').click();
//   await page.getByRole('button', { name: 'create' }).click();
//   await page.getByText('School Details created').click();
//   await page.getByRole('link', { name: 'Dashboard' }).click();
//   await page.getByText('Manage Subject').click();
//   await page.getByRole('link', { name: 'Manage Major Subject' }).click();
//   await page.locator('div').filter({ hasText: /^Select Classnurserykg1$/ }).getByRole('combobox').selectOption('x3sih05fuiX0,kg1');
//   await page.locator('div').filter({ hasText: /^Selectkg1-A-2025kg1-B-2025kg1-C-2025kg1-D-2025$/ }).getByRole('combobox').selectOption('mhlx8oQk7oUT,kg1-A-2025');
//   await page.getByRole('button', { name: '+ ADD SUBJECT' }).click();
//   await page.getByPlaceholder('Enter Subject Name').click();
//   await page.getByPlaceholder('Enter Subject Name').fill('english');
//   await page.getByPlaceholder('Enter Subject Code').click();
//   await page.getByPlaceholder('Enter Subject Code').fill('01');
//   await page.getByPlaceholder('Enter Days Per Week').click();
//   await page.getByPlaceholder('Enter Days Per Week').fill('5');
//   await page.getByRole('button', { name: 'Submit' }).click();
//   await page.getByRole('button', { name: '+ ADD SUBJECT' }).click();
//   await page.getByPlaceholder('Enter Subject Name').click();
//   await page.getByPlaceholder('Enter Subject Name').fill('hindi');
//   await page.locator('div:nth-child(2) > .relative > .inline-flex').first().click();
//   await page.getByPlaceholder('Enter Subject Code').fill('02');
//   await page.getByPlaceholder('Enter Days Per Week').click();
//   await page.getByPlaceholder('Enter Days Per Week').fill('5');
//   await page.getByRole('button', { name: 'Submit' }).click();
//   await page.getByRole('button', { name: '+ ADD SUBJECT' }).click();
//   await page.getByPlaceholder('Enter Subject Name').click();
//   await page.getByPlaceholder('Enter Subject Name').fill('maths');
//   await page.getByPlaceholder('Enter Subject Code').click();
//   await page.getByPlaceholder('Enter Subject Code').fill('03');
//   await page.getByPlaceholder('Enter Days Per Week').click();
//   await page.getByPlaceholder('Enter Days Per Week').fill('5');
//   await page.getByRole('button', { name: 'Submit' }).click();
//   await page.getByRole('button', { name: '+ ADD SUBJECT' }).click();
//   await page.getByPlaceholder('Enter Subject Name').click();
//   await page.getByPlaceholder('Enter Subject Name').fill('science');
//   await page.getByPlaceholder('Enter Subject Code').click();
//   await page.getByPlaceholder('Enter Subject Code').fill('04');
//   await page.getByPlaceholder('Enter Days Per Week').click();
//   await page.getByPlaceholder('Enter Days Per Week').fill('5');
//   await page.getByRole('button', { name: 'Submit' }).click();
//   await page.getByRole('link', { name: 'Manage Subject' }).click();
//   await page.getByLabel('Breadcrumbs').getByText('Home').click();
//   await page.getByText('Manage Exam').click();
//   await page.getByRole('link', { name: 'Manage Grade' }).click();
//   await page.getByRole('button', { name: 'Add Grading Group' }).click();
//   await page.getByLabel('Name *').click();
//   await page.getByLabel('Name *').fill('test');
//   await page.getByRole('button', { name: 'Add' }).click();
//   await page.getByRole('button', { name: 'Open test Click To See Grade' }).click();
//   await page.getByRole('button', { name: 'Open test Click To See Grade' }).click();
//   await page.getByRole('button', { name: 'Open test Click To See Grade' }).click();
//   await page.getByRole('link', { name: 'Manage Exam' }).click();
//   await page.getByRole('link', { name: 'Manage Division' }).click();
//   await page.locator('div').filter({ hasText: /^Class \* Select ClassNurseryKg1$/ }).getByRole('combobox').selectOption('x3sih05fuiX0');
//   await page.getByRole('button', { name: 'Add Division Group' }).click();
//   await page.getByLabel('Name *').click();
//   await page.getByLabel('Name *').fill('test');
//   await page.getByRole('button', { name: 'Add' }).click();
//   await page.getByRole('button', { name: 'Open test Click To See' }).click();
//   await page.getByRole('button', { name: 'Open test Click To See' }).click();
//   await page.getByRole('button', { name: 'Open test Click To See' }).click();
//   await page.locator('div').filter({ hasText: /^Class \* Select ClassNurseryKg1$/ }).getByRole('combobox').selectOption('');
//   await page.locator('div').filter({ hasText: /^Class \* Select ClassNurseryKg1$/ }).getByRole('combobox').selectOption('x3sih05fuiX0');
//   await page.getByRole('link', { name: 'Manage Exam' }).click();
//   await page.getByRole('link', { name: 'Manage Exam Group' }).click();
//   await page.getByPlaceholder('ex: QUARTERLY').click();
//   await page.getByPlaceholder('ex: QUARTERLY').fill('final');
//   await page.locator('div').filter({ hasText: /^Select ClassNurseryKg1$/ }).getByRole('combobox').selectOption('x3sih05fuiX0,Kg1');
//   await page.getByLabel('Kg1-A-').check();
//   await page.getByPlaceholder('ex: QUARTERLY').click();
//   await page.getByPlaceholder('ex: QUARTERLY').fill('final');
//   await page.locator('div').filter({ hasText: /^Exam Type \* SelectMarksGradeGrade and Marks$/ }).getByRole('combobox').selectOption('Marks');
//   await page.locator('div').filter({ hasText: /^Select Grade Grouptest$/ }).getByRole('combobox').selectOption('9UQktLPothHp');
//   await page.getByRole('button', { name: 'Add Group' }).click();
//   await page.locator('div').filter({ hasText: /^Select Grade Grouptest$/ }).getByRole('img').click();
//   await page.locator('div').filter({ hasText: /^Select Grade Grouptest$/ }).getByRole('img').click();
//   await page.locator('div').filter({ hasText: /^Select Grade Grouptest$/ }).getByRole('combobox').selectOption('');
//   await page.getByRole('button', { name: 'Add Group' }).click();
//   await page.getByRole('main').getByText('Successfully Added Group(s)').click();
//   await page.getByRole('button', { name: 'final' }).click();
//   await page.locator('[id="react-aria1207494108-\\:r9a\\:"]').fill('2025-01-01');
//   await page.locator('[id="react-aria1207494108-\\:r9f\\:"]').click();
//   await page.locator('div').filter({ hasText: /^All Maximum Marks$/ }).locator('div').nth(3).click();
//   await page.locator('[id="react-aria1207494108-\\:r9f\\:"]').fill('99');
//   await page.locator('div').filter({ hasText: /^All Minimum Marks$/ }).locator('div').nth(3).click();
//   await page.locator('[id="react-aria1207494108-\\:r9k\\:"]').fill('33');
//   await page.locator('div').filter({ hasText: /^All Start Time$/ }).locator('div').nth(3).click();
//   await page.locator('[id="react-aria1207494108-\\:r9p\\:"]').fill('09:00');
//   await page.locator('div').filter({ hasText: /^All End Time$/ }).locator('div').nth(2).click();
//   await page.locator('[id="react-aria1207494108-\\:r9u\\:"]').fill('12:00');
//   await page.getByRole('button', { name: 'Submit' }).click();
//   await page.getByRole('main').getByText('Successfully Added Exams').nth(3).click();
//   await page.getByRole('button', { name: 'Publish' }).click();
//   await page.getByText('Manage Exam /').click();
//   await page.getByRole('link', { name: 'Assign Marks' }).click();
//   await page.locator('div').filter({ hasText: /^Class \* Select ClassNurseryKg1$/ }).getByRole('combobox').selectOption('x3sih05fuiX0,Kg1');
//   await page.locator('div').filter({ hasText: /^SelectKg1-A-2025Kg1-B-2025Kg1-C-2025Kg1-D-2025$/ }).getByRole('combobox').selectOption('mhlx8oQk7oUT,Kg1-A-2025');
//   await page.locator('div').filter({ hasText: /^Group \* SelectFinal$/ }).getByRole('combobox').selectOption('9pbfLIZXITM4,Final');
//   await page.getByRole('button', { name: 'Assign' }).first().click();
//   await page.locator('[id="react-aria1207494108-\\:rdt\\:"]').click();
//   await page.locator('[id="react-aria1207494108-\\:rdt\\:"]').fill('80');
//   await page.locator('[id="react-aria1207494108-\\:re8\\:"]').click();
//   await page.locator('[id="react-aria1207494108-\\:re8\\:"]').fill('70');
//   await page.getByRole('button', { name: 'Submit Marks' }).click();
//   await page.getByText('Successfully Added Score').nth(3).click();
//   await page.locator('div').filter({ hasText: /^Class \* Select ClassNurseryKg1$/ }).getByRole('combobox').selectOption('x3sih05fuiX0,Kg1');
//   await page.locator('div').filter({ hasText: /^SelectKg1-A-2025Kg1-B-2025Kg1-C-2025Kg1-D-2025$/ }).getByRole('combobox').selectOption('mhlx8oQk7oUT,Kg1-A-2025');
//   await page.locator('div').filter({ hasText: /^Group \* SelectFinal$/ }).getByRole('combobox').selectOption('9pbfLIZXITM4,Final');
//   await page.getByRole('button', { name: 'Assign' }).nth(1).click();
//   await page.locator('[id="react-aria1207494108-\\:rev\\:"]').click();
//   await page.locator('[id="react-aria1207494108-\\:rev\\:"]').fill('90');
//   await page.locator('tr:nth-child(2) > td:nth-child(4) > .group > div > .relative > .inline-flex').click();
//   await page.locator('[id="react-aria1207494108-\\:rfa\\:"]').fill('80');
//   await page.getByRole('button', { name: 'Submit Marks' }).click();
//   await page.getByText('Successfully Added Score').nth(3).click();
//   await page.locator('div').filter({ hasText: /^Class \* Select ClassNurseryKg1$/ }).getByRole('combobox').selectOption('x3sih05fuiX0,Kg1');
//   await page.getByText('Batch *SelectKg1-A-2025Kg1-B-').click();
//   await page.locator('div').filter({ hasText: /^SelectKg1-A-2025Kg1-B-2025Kg1-C-2025Kg1-D-2025$/ }).getByRole('combobox').selectOption('mhlx8oQk7oUT,Kg1-A-2025');
//   await page.locator('div').filter({ hasText: /^Group \* SelectFinal$/ }).getByRole('combobox').selectOption('9pbfLIZXITM4,Final');
//   await page.getByRole('button', { name: 'Assign' }).nth(2).click();
//   await page.locator('[id="react-aria1207494108-\\:rg1\\:"]').click();
//   await page.locator('[id="react-aria1207494108-\\:rg1\\:"]').fill('88');
//   await page.locator('[id="react-aria1207494108-\\:rgc\\:"]').click();
//   await page.locator('[id="react-aria1207494108-\\:rgc\\:"]').fill('77');
//   await page.getByRole('button', { name: 'Submit Marks' }).click();
//   await page.getByText('Class * Select ClassNurseryKg1').click();
//   await page.locator('div').filter({ hasText: /^SelectKg1-A-2025Kg1-B-2025Kg1-C-2025Kg1-D-2025$/ }).getByRole('combobox').selectOption('mhlx8oQk7oUT,Kg1-A-2025');
//   await page.locator('div').filter({ hasText: /^Group \* SelectFinal$/ }).getByRole('combobox').selectOption('9pbfLIZXITM4,Final');
//   await page.getByRole('button', { name: 'Assign' }).nth(3).click();
//   await page.locator('[id="react-aria1207494108-\\:rh3\\:"]').click();
//   await page.locator('[id="react-aria1207494108-\\:rh3\\:"]').fill('80');
//   await page.locator('tr:nth-child(2) > td:nth-child(4) > .group > div > .relative > .inline-flex').click();
//   await page.locator('[id="react-aria1207494108-\\:rhe\\:"]').fill('60');
//   await page.getByRole('button', { name: 'Submit Marks' }).click();
//   await page.getByText('Successfully Added Score').nth(3).click();
//   await page.getByRole('link', { name: 'Manage Exam' }).click();
//   await page.getByRole('link', { name: 'Exam Report Before Publish' }).click();
//   await page.locator('div').filter({ hasText: /^Select Classnurserykg1$/ }).getByRole('img').click();
//   await page.locator('div').filter({ hasText: /^Select Classnurserykg1$/ }).getByRole('combobox').selectOption('x3sih05fuiX0,kg1');
//   await page.locator('div').filter({ hasText: /^Selectkg1-A-2025kg1-B-2025kg1-C-2025kg1-D-2025$/ }).getByRole('combobox').selectOption('mhlx8oQk7oUT,kg1-A-2025');
//   await page.locator('div').filter({ hasText: /^Group \* Selectfinal$/ }).getByRole('combobox').selectOption('9pbfLIZXITM4-undefined');
//   await page.getByRole('cell', { name: 'rishu' }).click();
//   await page.getByRole('cell', { name: 'test' }).click();
//   await page.getByText('Overall Class Percentage').click();
//   await page.getByRole('link', { name: 'Manage Exam' }).click();
//   await page.getByRole('link', { name: 'Publish Result', exact: true }).click();
//   await page.locator('div').filter({ hasText: /^Select ClassNurseryKg1$/ }).getByRole('combobox').selectOption('x3sih05fuiX0,Kg1');
//   await page.locator('div').filter({ hasText: /^SelectKg1-A-2025Kg1-B-2025Kg1-C-2025Kg1-D-2025$/ }).getByRole('combobox').selectOption('mhlx8oQk7oUT,Kg1-A-2025');
//   await page.locator('div').filter({ hasText: /^Group \* SelectFinal$/ }).getByRole('combobox').selectOption('9pbfLIZXITM4-undefined');
//   await page.getByRole('button', { name: 'Publish Result', exact: true }).click();
//   await page.getByLabel('Final').getByText('Final').click();
//   await page.getByText('Marks').click();
//   await page.getByLabel('Final').getByText('Kg1-A-').click();
//   await page.getByText('11-07-').click();
//   await page.getByRole('link', { name: 'Manage Exam' }).click();
//   await page.getByRole('link', { name: 'Manage Weightage Template' }).click();
//   await page.locator('div').filter({ hasText: /^Assign Template$/ }).nth(1).click();
//   await page.getByLabel('Select a Class').click();
//   await page.getByLabel('kg1', { exact: true }).getByText('kg1').click();
//   await page.getByLabel('Select a Section').click();
//   await page.getByLabel('kg1-A-2025', { exact: true }).getByText('kg1-A-').click();
//   await page.getByLabel('Select a Template Name').click();
//   await page.locator('[id="react-aria1207494108-\\:rnn\\:"]').click();
//   await page.getByRole('button', { name: 'Select a Type Personal Detail' }).click();
//   await page.getByLabel('Normal', { exact: true }).click();
//   await page.getByLabel('Yes / No').click();
//   await page.getByLabel('Yes', { exact: true }).click();
//   await page.getByLabel('Select a Type').click();
//   await page.getByLabel('Advance', { exact: true }).getByText('Advance').click();
//   await page.getByLabel('Select a Color').click();
//   await page.getByLabel('Red', { exact: true }).getByText('Red').click();
//   await page.getByLabel('Select a Border Type').click();
//   await page.getByLabel('Thick ===========', { exact: true }).getByText('Thick ===========').click();
//   await page.getByLabel('Select a Border Color').click();
//   await page.getByLabel('Red', { exact: true }).getByText('Red').click();
//   await page.getByLabel('Select a Heading Color').click();
//   await page.getByLabel('Green', { exact: true }).getByText('Green').click();
//   await page.getByLabel('(Recomended - 20)').click();
//   await page.getByLabel('16', { exact: true }).getByText('16').click();
//   await page.getByLabel('16,').click();
//   await page.getByLabel('20', { exact: true }).click();
//   await page.getByLabel('Font Style', { exact: true }).click();
//   await page.getByLabel('Times', { exact: true }).getByText('Times').click();
//   await page.getByLabel('(Recomended - 10/12)').click();
//   await page.getByLabel('10', { exact: true }).getByText('10').click();
//   await page.getByLabel('(Recomended - 25)').click();
//   await page.getByLabel('30', { exact: true }).getByText('30').click();
//   await page.getByLabel('30,').click();
//   await page.getByLabel('25', { exact: true }).getByText('25').click();
//   await page.getByLabel('Student Image ?').click();
//   await page.getByLabel('Yes', { exact: true }).getByText('Yes').click();
//   await page.getByRole('button', { name: 'Submit' }).click();
//   await page.getByRole('link', { name: 'Manage Exam' }).click();
//   await page.getByRole('link', { name: 'Exam Report For School' }).click();
//   await page.locator('div').filter({ hasText: /^Select ClassNurseryKg1$/ }).getByRole('combobox').selectOption('x3sih05fuiX0,Kg1');
//   await page.getByText('Batch *SelectKg1-A-2025Kg1-B-').click();
//   await page.locator('div').filter({ hasText: /^SelectKg1-A-2025Kg1-B-2025Kg1-C-2025Kg1-D-2025$/ }).getByRole('combobox').selectOption('mhlx8oQk7oUT,Kg1-A-2025,');
//   await page.locator('div').filter({ hasText: /^Group \* SelectFinal$/ }).getByRole('combobox').selectOption('9pbfLIZXITM4-Final');
//   await page.locator('div').filter({ hasText: /^Student \* SelectRishuTest$/ }).getByRole('combobox').selectOption('EK66476lqMPO-Rishu');
//   await page.getByRole('cell', { name: 'ENGLISH' }).click();
//   await page.getByRole('cell', { name: 'HINDI' }).click();
//   await page.getByRole('cell', { name: 'MATHS' }).click();
//   await page.getByRole('cell', { name: 'SCIENCE' }).click();
//   const page1Promise = page.waitForEvent('popup');
//   await page.getByRole('button', { name: 'Print' }).click();
//   const page1 = await page1Promise;
// });




// test('test', async ({ page }) => {
//   await page.goto('https://testschool.launchmysite.in/');
//   await page.getByPlaceholder('Enter your Email').click();
//   await page.getByPlaceholder('Enter your Email').fill('test@example.com');
//   await page.getByPlaceholder('Enter your password').click();
//   await page.getByPlaceholder('Enter your password').fill('test@123');
//   await page.getByRole('button', { name: 'Sign In' }).click();
//   await page.locator('div:nth-child(2) > div:nth-child(4)').first().click();
//   await page.getByRole('link', { name: 'Manage Employee Category' }).click();
//   await page.getByPlaceholder('Enter category name').click();
//   await page.getByPlaceholder('Enter category name').fill('first division');
//   await page.getByPlaceholder('Enter prefix').click();
//   await page.getByPlaceholder('Enter prefix').fill('test');
//   await page.getByRole('button', { name: 'Save' }).click();
//   await page.getByRole('link', { name: 'HR Management' }).click();
//   await page.getByRole('link', { name: 'Employee department' }).click();
//   await page.getByPlaceholder('Enter name').click();
//   await page.locator('div').filter({ hasText: /^Name \*$/ }).locator('div').nth(2).click();
//   await page.getByPlaceholder('Enter name').fill('first div');
//   await page.locator('div').filter({ hasText: /^Code \*Max 5 characters$/ }).locator('div').nth(2).click();
//   await page.getByPlaceholder('Enter code').fill('test');
//   await page.getByRole('button', { name: 'Save' }).click();
//   await page.locator('div').filter({ hasText: /^Code \*Max 5 characters$/ }).locator('div').nth(2).click();
//   await page.getByPlaceholder('Enter code').fill('test1');
//   await page.getByRole('button', { name: 'Save' }).click();
//   await page.getByRole('table').locator('div').filter({ hasText: 'Created successfully' }).nth(2).click();
//   await page.getByRole('link', { name: 'HR Management' }).click();
//   await page.getByLabel('Breadcrumbs').getByText('Home').click();
//   await page.locator('.mt-4 > div > .grid > div:nth-child(2)').first().click();
//   await page.getByRole('link', { name: 'Employee Admission' }).click();
//   await page.locator('input[name="employee_number"]').click();
//   await page.locator('input[name="employee_number"]').fill('01');
//   await page.getByPlaceholder('Enter your first name').click();
//   await page.getByPlaceholder('Enter your first name').fill('test');
//   await page.locator('input[name="dob"]').fill('2000-01-01');
//   await page.getByPlaceholder('example@gmail.com').click();
//   await page.getByPlaceholder('example@gmail.com').fill('test@gmail.com');
//   await page.getByPlaceholder('Enter your password').click();
//   await page.getByPlaceholder('Enter your password').fill('test@1');
//   await page.locator('select[name="employee_department"]').selectOption('rUCfBpXTlyxU');
//   await page.locator('select[name="employeecategories"]').selectOption('NBVTvQS6CItk');
//   await page.getByPlaceholder('please enter 10 digit mobile').click();
//   await page.getByPlaceholder('please enter 10 digit mobile').fill('9876543218');
//   await page.getByLabel('Select Role').click();
//   await page.getByLabel('Class Teacher', { exact: true }).click();
//   await page.getByText('Submit').click();
//   await page.getByRole('main').locator('div').filter({ hasText: /^Successfully Added Emp$/ }).nth(2).click();
//   await page.getByRole('main').locator('div').filter({ hasText: /^Successfully Register Employee$/ }).nth(1).click();
// });